SET ANSI ON
SET AUTOSAVE ON
SET BELL OFF
SET BELL TO 400,2
SET BLINK ON
SET BRSTATUS OFF
SET CARRY OFF
SET CENTURY ON
SET CLEAR OFF
SET CLOCK OFF
SET CONFIRM OFF
SET CONSOLE ON
SET CURSOR ON
SET DATE DMY
SET DEBUG OFF
SET DECIMAL TO 16
SET DELETE ON
SET DELIM OFF
SET DEVE ON
SET DEVI TO SCREEN
SET DOHI OFF
SET ECHO OFF
SET ESCAPE OFF
SET EXACT OFF
SET EXCLUS OFF
SET FIELD TO
SET FIXED OFF
SET FORMAT TO
SET FULLP ON
SET HEAD OFF
SET HELP OFF
SET HOURS TO 24
SET KEYCOMP TO DOS
SET LOCK OFF
SET MARK TO "-"
SET MARGIN TO 0
SET MEMO TO 72
SET MOUSE ON
SET MULTI ON
SET NEAR OFF
SET NOTI OFF
SET OPTI ON
SET PALETTE ON
SET POINT TO "'"
SET PRINT OFF
SET PRINT TO
SET PROCE TO
SET REFRE TO 1
SET REPRO TO 0
SET SAFE OFF
SET SCOR OFF
SET SEPA TO "."
SET SHADOW ON
* SET STAT OFF
SET STEP OFF
SET STICKY ON
SET TALK OFF
SET TEXTM OFF
SET TYPEA TO 50
SET UDFPA TO VALUE
SET UNIQUE OFF
SET VIEW OFF
SET FUNC  2 TO ""
SET FUNC  3 TO ""
SET FUNC  4 TO ""
SET FUNC  5 TO ""
SET FUNC  6 TO ""
SET FUNC  7 TO ""
SET FUNC  8 TO ""
SET FUNC  9 TO ""
SET FUNC 10 TO ""
*
SET BELL ON
SET CONFIRM OFF
SET EXCLUS OFF
SET DATE BRITI
SET CENTU ON
SET DELE ON
SET STATUS BAR OFF
SET CLOCK STATUS
SET MESSAGE ON
SET MESSAGE TO ""
SET TALK OFF
SET ECHO OFF
SET SAFE OFF

SET NOTIFY OFF
SET CONSOLE OFF
SET CURRENCY TO "R$"
SET POINT TO ","
SET SEPARATOR TO "."
SET ENGINEBEHAVIOR 70

SET EXCLUSIVE OFF
SET REPROCESS TO 5
SET REFRESH TO 5
SET STATUS off
